### ISSUE TITLE
Add loots chests

### ISSUE THREAD

**Issue by juanj** [bitquest/bitquest#109]
Add a special type of chest with rewards that players can only take once. This will be good for parkour, dungeons, and treasure hunt.

**Comment by CubeFromSpace** [comment]
Fun idea: make them fall from the sky as tagged chests that disappear after 12 hours, and they reward bitcoin instead of items

**Comment by theraccoonbear** [comment]
@CubeFromSpace where would these BTC be coming from? Will you be donating them?

**Comment by CubeFromSpace** [comment]
Maybe if I can get an external wallet first. Then I would totally donate.

**Comment by theraccoonbear** [comment]
Wallets are easy and cheap to get.  Coins to put in them?  Less so.

**Comment by CubeFromSpace** [comment]
I intended to convert USD to BTC

**Comment by theraccoonbear** [comment]
My point is that the money has to come from somewhere, and without an indefinite benefactor/patron (will that be you?) the well will dry up.  Case in point: ongoing issues with the fee wallet and stuck transactions.

**Comment by CubeFromSpace** [comment]
I'm not trying to be rude, but maybe it can be funded regularly like mob loot.

**Comment by Burntuno** [comment]
In Bitquest, all treasures have been provided by players and not just created magically with creative.  Having chests like that sounds cool, but I'm not sure how they will get the prizes.  Also I don't like any automatic way of obtaining server funds.  Fighting mobs is just part of the lottery type distribution forcing players to do the time.  Having users obtain bits from chests or selling to villagers is very easy to abuse with fake accounts and duplications.  Trading with other players is a way to build community and gives the players the ability to make own circumstances, since they provide the rewards anyway.  Funding loot is easy now; deposit to villager/loot address or get something for it by buying Elytra, etc.  If you like to help new players, just make simple buys from them, to help them start out.  Watch the blockchain and you can easily see if they claim or pull the funds out and run.  It is very transparent this way.

**Comment by juanj** [comment]
I agree.
I was thinking that the loot chests can give rare items not bits.

**Comment by theraccoonbear** [comment]
@CubeFromSpace my comment was in regards to the original sense of the word Patron, not the current fadish crowdfunding site.  I don't believe either would work.

**Comment by CubeFromSpace** [comment]
Ok, I'm so stupid :P

**Comment by CubeFromSpace** [comment]
At this point, the issue isn't really valid anymore, I guess.

**Comment by juanj** [comment]
Why not? 
This isn't implemented yet, so this can stay open for further discussion.

**Comment by CubeFromSpace** [comment]
My idea of bit loots from it was crushed, and burnt explained how the item loots are unfair

**Comment by juanj** [comment]
Enchanted armor? Swords? Elitras? Rare blocks? I think of many possible reward

**Comment by CubeFromSpace** [comment]
Read the above comment by burntuno

**Comment by CubeFromSpace** [comment]
Burntuno was saying how the loots in bitquest are funded by players. Not made magically.

**Comment by CubeFromSpace** [comment]
This issue is still no longer useful. Seriously, @Burntuno said that they are not created magically in creative, and that they are all player funded

**Comment by CubeFromSpace** [comment]
I had a new plan

**Comment by CubeFromSpace** [comment]
Because @explodi just implemented the new Xapo system, we can now have in game transactions less than 200, (but not external ones). The loot is WAY less now, only 1-5b per overworld mob, but maybe we can make loot chests worth ~10-15b each, albeit still rarer.

**Comment by theraccoonbear** [comment]
I'm not really clear what your idea is, but I'll happily criticize once I understand it.

**Comment by CubeFromSpace** [comment]
You can make transactions less than 200 bits

Loot chests may be able to work, being about 10-15 bits, about the same as 1-2 low level pigmen with the new loot system

This may work (unless @theraccoonbear says how it won't) except with no item loots at all, in the same sense that those have value

**Comment by CubeFromSpace** [comment]
@theraccoonbear you forgot to criticize me

**Comment by theraccoonbear** [comment]
I don't criticize you, I criticize ideas if I think they need to be refined

**Comment by CubeFromSpace** [comment]
Ok
