### ISSUE TITLE
We need a solution to this crashing

### ISSUE THREAD

**Issue by CubeFromSpace** [bitquest/bitquest#127]
We need to know exactly how crashes happen, and find a way to reverse it. Any ideas?

**Comment by CubeFromSpace** [comment]
I've heard that some of them involve the BQ wallet crashing. @explodi how does it crash.

I've also heard about land ownership causing some crashes, involving the REDIS servers.

**Comment by CubeFromSpace** [comment]
Earlier, I think explodi solved it.

**Comment by explodi** [comment]
Happy to see this closed. The issue was making use of redis while on scheduled tasks. We used to refresh the user's balance (scoreboard) using this method (a task that runs every 100 seconds). In new versions of BitQuest the balance scoreboard is refreshed on certain events (like after a purchase or walking from one chunk to another)

Since BitQuest now supports Bitcore apart from Blockcypher there is no need do do balance caches anymore so in future versions the balance scoreboard refresh will be back.

**Comment by CubeFromSpace** [comment]
Wonderful!
