### ISSUE TITLE
Change BitQuest variable storage techniques

### ISSUE THREAD

**Issue by Xeyler** [bitquest/bitquest#167]
Since BitQuest 2.0, we've used REDIS and environment variables to store variables. I think we should do some things to make BitQuest more user-friendly in maintenance and setting up:

1. Use MySQL instead of REDIS
2. Use a [config.yml](https://www.spigotmc.org/wiki/config-files/) instead of environment variables

A migration to MySQL could require a fair amount of work. It's also pretty likely that whoever plans to set up a BitQuest environment would be able to use REDIS instead of MySQL. We'd need a professional opinion on making this change or not.

Using a config.yml instead of environment variables would be pretty easy, though. I think a config file would also be much easier to access, read, and edit. After all, Spigot did intend plugin config files to be used in this way.

Overall, though, MySQL and plugins' config files seem to be more popular ways to store data and variables.

**Comment by theraccoonbear** [comment]
Oof, I vote we keep MySQL as far away from this as possible.  If we want an RDBMS (do we really? what's the use case?) I vote for PostgreSQL.  If you're running/deving with Docker (the preferred setup, last I saw?) getting REDIS up is dead simple (as would be MySQL, Postgres, et al).  Likewise, `docker-compose.yml` makes storing those env vars in a YAML file easy and "just works" with Docker.  Just my $0.02

**Comment by Shiny-andKittens** [comment]
I think it may be too hard to switch to a new database now that we use it so much in the plugin, but it may be possible if we all agree.

**Comment by explodi** [comment]
using sql is a lot more work and creates vectors for attacks as the language is more complex and injectable. this must be considered before making the change to a new database system. on the other hand the simplicity of redis which cannot perform complex operations but fast and simple ones also make the code more auditable.

**Comment by jadiesel** [comment]
Barefoot Bob here, FYI.   I've been a DB professional for over 30 years - and run a couple different development projects today. I just had to interject my thoughts.  There is nothing wrong with Redis for simple, quick transactions. The problem with Redis is two-fold though: It is memory resident, so the more you use it (the bigger the load), the more memory you chew up and need. This can easily lead to memory conflicts with other in-memory applications, like, oh Java. The second is the cache system. It is extremely file system dependent, and you can actually have conflicts between drivers in Linux and the hard drive cache system itself. In other words, if you are on your own physical system, you turn off disk cache at the system level, let Redis do it's own thing and you prevent most problems. I've also noticed alarge amount of people having problems when using Redis in t he Docker environment.

Take that for what it's worth, but I can easily see issues resulting from the combination of Java/Redis/Docker

To be honest, I know very few people that still rely on Redis for production, mainly because of the memory issues. It can and does cause problems.  My devs with  strong json/javascript abilities prefer nosql (mongo mainly), while I'm still a fan of a RDBMS in almost any form. PostOgre is good if you maintain your own, but I have been smitten by Azure and the beauty of separating the database from the app server altogether,

Just thoughts - It's  pain to change a backend system - hell, it can be hard to switch between versions of SQL... but there is a reason DB pros like the RDBMS systems and the Devs like nosql and document based systems. 

Anyway, just my 2 cents since you discussing it :)
