### ISSUE TITLE
DQ /currency emerald says it works but see no changes?

### ISSUE THREAD

**Issue by AltQuest** [bitquest/bitquest#283]
it lets me use /currency emerald or /currency doge but doesnt change anything on scoreboard.

**Comment by shishir9747** [comment]
how did you build jar file? I did mvn package -B but it showing
COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.742 s
[INFO] Finished at: 2020-06-27T18:32:47+06:00
