### ISSUE TITLE
Crops on claimed lands can be trampled be other players

### ISSUE THREAD

**Issue by u8iuui11** [bitquest/bitquest#287]

**Comment by masecla22** [comment]
Issue is fixed in #288 pull request. Waiting on @explodi to merge!

**Comment by shishir9747** [comment]
how did you build jar file? I did mvn package -B but it showing
COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.742 s
[INFO] Finished at: 2020-06-27T18:32:47+06:00
