### ISSUE TITLE
/land transfer <username>

### ISSUE THREAD

**Issue by syrianrue** [bitquest/bitquest#289]
/land transfer <username> seems to be broken. i just says "cannot find player <username>". i didnt have a sign to try with

**Comment by QuintLeo** [comment]
Land purchases also appear to be broken on Bitquest - keeps saying it can't complete try again later.
Have tried both /land  and a sign.

**Comment by shishir9747** [comment]
how did you build jar file? I did mvn package -B but it showing
 COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.742 s
[INFO] Finished at: 2020-06-27T18:32:47+06:00

**Comment by QuintLeo** [comment]
I'm not running Bitquest, I'm just one of the folks that used to play on the old Bitquest and later Dogequest servers.
     On Saturday, June 27, 2020, 05:33:24 AM PDT, shishir9747 <notifications@github.com> wrote:  
 
 


how did you build jar file? I did mvn package -B but it showing
COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.742 s
[INFO] Finished at: 2020-06-27T18:32:47+06:00

**Comment by shishir9747** [comment]
Can you help me to create a jar file pls. or a server which use bitquest

**Comment by QuintLeo** [comment]
No I can't.
I don't run such a server nor have I ever looked at the code itself.
I would suggest you try to contact "exploti" the original author, or BitcoinJake09 who is doing active development work AND running a server on a fork of the code.     On Wednesday, July 8, 2020, 11:31:20 PM PDT, shishir9747 <notifications@github.com> wrote:  
 
 


Can you help me to create a jar file pls. or a server which use bitquest

**Comment by BitcoinJake09** [comment]
BitcoinJake09@gmail.com
