### ISSUE TITLE
Anvil uses XP

### ISSUE THREAD

**Issue by RagingMouser** [bitquest/bitquest#29]
Not sure if this is a defect or intentional. Enchanting or combining enchantments effectively costs no XP.

Steps to reproduce:
1. Take note of your current XP level
2. Enchant a book/tool/weapon or combine enchanted items on the anvil.
3. Notice that your XP level has dropped like it would in Vanilla.
4. Force your XP to refresh by reconnecting to the server or killing a hostile mob.
5. Notice that your XP level is back to where it was before it was spent.

**Comment by juanj** [comment]
Is intencional.
What needs to be fix is to not lose the xp.

**Comment by RagingMouser** [comment]
OK. I'll make a pull request to prevent the loss of XP.

**Comment by RagingMouser** [comment]
#30 addresses the enchanting table piece. I still need to fix the anvil piece.

**Comment by Xeyler** [comment]
Perhaps we should disable exp orb spawning as well? They don't really matter, but they are kind of an aesthetic nuisance to me because they don't do anything, and should therefore be removed.

**Comment by CubeFromSpace** [comment]
I think the solution could be to disable the event of exp loss before the anvil event is completed. Then it would prevent the loss of exp

**Comment by Burntuno** [comment]
Anvil does not take your Level.  Indicator and level number usually has issues and bugs because of your client not being modified for Bitquests custom system.  A few different things like killing mobs, relogs, etc. resets the level to correct value.  We definitely don't want to get rid of EXP orbs.  They are useful to the many players who have Mending gear now.  Keep the orbs, for sure.

**Comment by theraccoonbear** [comment]
Agreed, in particular re: mending since I have a few items now.

**Comment by CubeFromSpace** [comment]
I experimented a little, and I think it has to to with vanilla Minecraft anvil behavior.
