### ISSUE TITLE
I can't connect to sever.

### ISSUE THREAD

**Issue by Mikilis** [bitquest/bitquest#290]
I can't connect to play.bitquest.co sever.
I use Minecraft 1.13.2.

**Comment by ShayGaming24** [comment]
That's because the server is not up yet. It should be released in less than 2 months.

**Comment by Mikilis** [comment]
Oh, no!

**Comment by shishir9747** [comment]
how did you build jar file? I did mvn package -B but it showing
COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.742 s
[INFO] Finished at: 2020-06-27T18:32:47+06:00
