### ISSUE TITLE
Players can access trapped chests in claimed chunks

### ISSUE THREAD

**Issue by nullpilot** [bitquest/bitquest#70]
As of right now, any player can access trapped chests on any other players claimed chunks.

The bug was brought to my attention by WeskerPrime, who also notified Burntone about the issue.

It should be a simple fix, so I gave it a go in PR #69. As you can tell from my profile I am new to this OSS thing, so I hope I went about this the right way.

I hope this helps!

**Comment by juanj** [comment]
You are right, trapped chests are not protected.
I do not think this was intentional but now I think, well, trapped chests are for traps and if a trap is in a not protected area don't make much sense. So being able to open (and active) a trap chest in a protected area is good for traps.
Also is good to have some kind of public chest
