### ISSUE TITLE
Current Bitcoin block height number added to /wallet

### ISSUE THREAD

**Issue by Airiellis** [bitquest/bitquest#89]
When you type in /wallet you see the current Bitcoin block height along with your balance and  address. User will be able to see if a block has cleared the blockchain or not. This would be a simple way to show our wallet is up to date with blockchain.

**Comment by Airiellis** [comment]
It would be very interesting to hear in-game sound "thunder and anvil" every time a block was solved in the blockchain. This happens every 10 minutes give or take.

**Comment by theraccoonbear** [comment]
What does "block has cleared the blockchain or not" mean?  Sorry, I'm not following.

**Comment by Airiellis** [comment]
Your wallet is sucks until your latest transaction inside a block is solved in the blockchain. All Bitcoin goes through the blockchain. Do you own bitcoin?

**Comment by Airiellis** [comment]
Having this feature would validate bitquest with real-time blocks. And other Bitcoin fans would be able to see what block we are on with blockchain. This is Burntone's idea. I thought it sounded good.

**Comment by theraccoonbear** [comment]
So, you want to see a list of pending transactions -- those not included in a 'confirmed' block; for some definition of 'confirmed', like 6 subsequent blocks above the transaction's -- for the user's wallet, if I'm understanding correctly.  I took a look at the [BlockCypher API documentation](https://dev.blockcypher.com) and while there's no doubt a way to do this, I'm not seeing an obvious way to list transactions for a given wallet.  We track user wallet balance, as reported by the BlockCypher API, but I don't see that we currently check any created transactions specifically.  At any rate, since a user can simply visit their wallet's URL on any number of blockchain monitoring sites (like BlockCypher), this seems somewhat unnecessary.  I'm not saying it can't be done, just that I think there's already good enough functionality outside of BitQuest to allow users to see the status of their in-game wallet and we might do better to work on BitQuest-specific functionality.

We do currently provide a link to the blockchain.info view of your wallet, when you run the `/wallet` command.  BlockCypher (whose API we use) provides an arguably better view of confirmed/unconfirmed transaction status.  Maybe a good middle ground would be updating the link to take the user to BlockCypher instead.  Thoughts?

**Comment by theraccoonbear** [comment]
@Airiellis I created a patch to update the link and sent a pull request.  I guess we'll see.  If we decide to do an in-game display approach, it'll involve a fair bit of coding against that BlockCypher API.  Hopefully this is an acceptable solution for now.

**Comment by Airiellis** [comment]
Yeah that looks good. I figured it would be hard to implement this. I will show this to Burntone.
